language: node_js
node_js:
- 7.7.1
notifications:
  email: false
  slack:
    secure: Qqhapu/J4G6qs4QSJIXEjpRTbFreipgGW3hUbLI4AbRhzfdpWuxf3D5cJuNh8bbHoIDt6OgW9oomvT401pXe0yakh5WN6RKIq8LOfn+UlUC7oaEVfg9ssJIi35goAmYjM2oBozlXwOmssMEihgsqY1Knr+Ld4KOJO2aE7F/qrXdG1aF2FIz42Pq5tZkbL263WmEFscBmIGO+yR1PvfX6gOrZbBmHc1KFBGT20uH7twLqqeCAtT5rww9nNTNc9EcUC8CECIYcncktE37wUFifGACuqWAmIfZGmdxeWidlnfs2t3gzEqaR+cakNo1BCLQBaEBcN7c5kv0cOnInQf38iyqqy8hf2lqiK/mRPwrTmrfhHbjmlMZQOzGe4aPVW+8jKyZ30aCZ2UXeMpaCbN/++NdbXok0hQQb0NAYf1ODkLAZIbuD3TUDHbN+zqiccZM0sww7l8OD73Ix4yAcxMq67Lcxc7vSdZQvuBemFtVIH0TgwV1kNkYFC3i6yesdAQkcLGaMRct7BgLWbW/dDgfMJWi4DU7OiuMFWTU592PI/MwfeopQrrLAU+AweiwHMhmtRzAD8kVl8APuZ2a/0RiuuSDUx179d4bOq8BQAflpAI59ULzqdkcPyQsP9GVVgQHpOKwdCMrXo1uj5/J6J/ve+kg8fszzllY5zB/LxSUQOAQ=
